cloudfront_url: "https://awesome-academy.com/"
local_cloudfront_url: "http://localhost:3000/"
author: "Framgia"
messages:
  success: "success"
  notice: "notice"
framgia:
  more_tool: "http://education.framgia.vn/tools"
  phone_text: "0914571991"
  phone_number: "0914571991"
  email: "info@awesome-academy.com"
  facebook: "http://www.facebook.com/framgia.awesome.academy/"
home:
  courses_limit: 10
  trainers_limit: 8
  trainer_quote_limit: 150
courses:
  length_description: 200
  per_page: 12
  popular: 4
  max_name_length: 255
  min_name_length: 3
  max_description_length: 1000
  min_description_length: 10
  money_unit: "VNĐ/tháng"
feedbacks:
  max_name_length: 127
  max_email_length: 127
  max_subject_length: 255
  max_content_length: 1023
  max_phone_length: 15
trainers:
  per_page: 20
certifications:
  min_name_length: 2
  max_name_length: 255
  max_description_length: 500
registrations:
  max_name_length: 127
  max_email_length: 127
  max_phone_length: 15
  max_address_length: 255
news:
  per_page: 20
  length_content: 320
  latest_news: 4
  popular_tags: 10
  max_title_length: 255
  short_content: 200
image_default:
  default: "/assets/default.jpg"
  user: "/assets/trainer_default.jpg"
news_category:
  min_name_length: 2
  max_name_length: 30
  max_description_length: 500
users:
  min_name_length: 2
  max_name_length: 30
  max_quote_length: 500
  min_phone_length: 10
  max_phone_length: 15
course_category:
  max_name_length: 255
course_registrations:
  reject: "reject"
course_schedules:
  per_page: 10
admin_page:
  per_page: 10
  page_default: 1
expires_cookie: 5
